Traceback (most recent call last):
  File "/home/airflow/venv/lib/python3.8/site-packages/psutil/_common.py", line 446, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1517, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/airflow/venv/lib/python3.8/site-packages/psutil/_common.py", line 449, in wrapper
    return fun(self)
  File "/home/airflow/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1559, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/home/airflow/venv/lib/python3.8/site-packages/psutil/_common.py", line 710, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/1831/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/venv/lib/python3.8/site-packages/psutil/__init__.py", line 352, in _init
    self.create_time()
  File "/home/airflow/venv/lib/python3.8/site-packages/psutil/__init__.py", line 708, in create_time
    self._create_time = self._proc.create_time()
  File "/home/airflow/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1517, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/airflow/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1729, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/home/airflow/venv/lib/python3.8/site-packages/psutil/_pslinux.py", line 1524, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=1831)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 479, in webserver
    monitor_gunicorn(gunicorn_master_proc.pid)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 444, in monitor_gunicorn
    GunicornMonitor(
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 212, in start
    self._check_workers()
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 258, in _check_workers
    num_workers_running = self._get_num_workers_running()
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 147, in _get_num_workers_running
    workers = psutil.Process(self.gunicorn_master_proc.pid).children()
  File "/home/airflow/venv/lib/python3.8/site-packages/psutil/__init__.py", line 324, in __init__
    self._init(pid)
  File "/home/airflow/venv/lib/python3.8/site-packages/psutil/__init__.py", line 365, in _init
    raise NoSuchProcess(pid, None, msg)
psutil.NoSuchProcess: psutil.NoSuchProcess no process found with pid 1831
