[2021-03-10 07:00:32,978] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: data_processing.is_api_available 2021-01-11T00:00:00+00:00 [queued]>
[2021-03-10 07:00:32,984] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: data_processing.is_api_available 2021-01-11T00:00:00+00:00 [queued]>
[2021-03-10 07:00:32,984] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-03-10 07:00:32,984] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-03-10 07:00:32,984] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-03-10 07:00:32,991] {taskinstance.py:1038} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-01-11T00:00:00+00:00
[2021-03-10 07:00:32,993] {standard_task_runner.py:51} INFO - Started process 42195 to run task
[2021-03-10 07:00:32,998] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'data_processing', 'is_api_available', '2021-01-11T00:00:00+00:00', '--job-id', '61', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_processing.py', '--cfg-path', '/tmp/tmpehiy0bjq']
[2021-03-10 07:00:32,998] {standard_task_runner.py:76} INFO - Job 61: Subtask is_api_available
[2021-03-10 07:00:33,158] {logging_mixin.py:103} INFO - Running <TaskInstance: data_processing.is_api_available 2021-01-11T00:00:00+00:00 [running]> on host airflowvm
[2021-03-10 07:00:33,284] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-01-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-11T00:00:00+00:00
[2021-03-10 07:00:33,284] {http.py:102} INFO - Poking: api/
[2021-03-10 07:00:33,287] {base.py:65} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: None
[2021-03-10 07:00:33,288] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-03-10 07:00:33,847] {base.py:245} INFO - Success criteria met. Exiting.
[2021-03-10 07:00:33,850] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=data_processing, task_id=is_api_available, execution_date=20210111T000000, start_date=20210310T070032, end_date=20210310T070033
[2021-03-10 07:00:33,868] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-10 07:00:33,901] {local_task_job.py:118} INFO - Task exited with return code 0
