[2021-03-10 07:04:26,601] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: data_processing.is_api_available 2021-02-01T00:00:00+00:00 [queued]>
[2021-03-10 07:04:26,607] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: data_processing.is_api_available 2021-02-01T00:00:00+00:00 [queued]>
[2021-03-10 07:04:26,607] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-03-10 07:04:26,607] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-03-10 07:04:26,607] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-03-10 07:04:26,615] {taskinstance.py:1038} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-02-01T00:00:00+00:00
[2021-03-10 07:04:26,616] {standard_task_runner.py:51} INFO - Started process 42963 to run task
[2021-03-10 07:04:26,622] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'data_processing', 'is_api_available', '2021-02-01T00:00:00+00:00', '--job-id', '166', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_processing.py', '--cfg-path', '/tmp/tmpp51f29yw']
[2021-03-10 07:04:26,622] {standard_task_runner.py:76} INFO - Job 166: Subtask is_api_available
[2021-03-10 07:04:26,771] {logging_mixin.py:103} INFO - Running <TaskInstance: data_processing.is_api_available 2021-02-01T00:00:00+00:00 [running]> on host airflowvm
[2021-03-10 07:04:26,902] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-01T00:00:00+00:00
[2021-03-10 07:04:26,902] {http.py:102} INFO - Poking: api/
[2021-03-10 07:04:26,905] {base.py:65} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: None
[2021-03-10 07:04:26,906] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-03-10 07:04:27,424] {base.py:245} INFO - Success criteria met. Exiting.
[2021-03-10 07:04:27,428] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=data_processing, task_id=is_api_available, execution_date=20210201T000000, start_date=20210310T070426, end_date=20210310T070427
[2021-03-10 07:04:27,447] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-10 07:04:27,451] {local_task_job.py:118} INFO - Task exited with return code 0
