[2021-03-10 07:02:23,771] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: data_processing.is_api_available 2021-01-21T00:00:00+00:00 [queued]>
[2021-03-10 07:02:23,777] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: data_processing.is_api_available 2021-01-21T00:00:00+00:00 [queued]>
[2021-03-10 07:02:23,777] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-03-10 07:02:23,777] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-03-10 07:02:23,777] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-03-10 07:02:23,785] {taskinstance.py:1038} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-01-21T00:00:00+00:00
[2021-03-10 07:02:23,787] {standard_task_runner.py:51} INFO - Started process 42562 to run task
[2021-03-10 07:02:23,791] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'data_processing', 'is_api_available', '2021-01-21T00:00:00+00:00', '--job-id', '111', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_processing.py', '--cfg-path', '/tmp/tmpdl_oocjj']
[2021-03-10 07:02:23,792] {standard_task_runner.py:76} INFO - Job 111: Subtask is_api_available
[2021-03-10 07:02:23,919] {logging_mixin.py:103} INFO - Running <TaskInstance: data_processing.is_api_available 2021-01-21T00:00:00+00:00 [running]> on host airflowvm
[2021-03-10 07:02:24,048] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-01-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-21T00:00:00+00:00
[2021-03-10 07:02:24,048] {http.py:102} INFO - Poking: api/
[2021-03-10 07:02:24,051] {base.py:65} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: None
[2021-03-10 07:02:24,052] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-03-10 07:02:24,542] {base.py:245} INFO - Success criteria met. Exiting.
[2021-03-10 07:02:24,545] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=data_processing, task_id=is_api_available, execution_date=20210121T000000, start_date=20210310T070223, end_date=20210310T070224
[2021-03-10 07:02:24,562] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-10 07:02:24,580] {local_task_job.py:118} INFO - Task exited with return code 0
