[2021-04-05 05:23:17,324] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: baxa_lead_importer.main 2021-04-05T05:00:00+00:00 [queued]>
[2021-04-05 05:23:17,396] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: baxa_lead_importer.main 2021-04-05T05:00:00+00:00 [queued]>
[2021-04-05 05:23:17,396] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-04-05 05:23:17,396] {taskinstance.py:1018} INFO - Starting attempt 7 of 8
[2021-04-05 05:23:17,396] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-04-05 05:23:17,447] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): main> on 2021-04-05T05:00:00+00:00
[2021-04-05 05:23:17,461] {standard_task_runner.py:51} INFO - Started process 35065 to run task
[2021-04-05 05:23:17,485] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'baxa_lead_importer', 'main', '2021-04-05T05:00:00+00:00', '--job-id', '301', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/baxa_lead_importer.py', '--cfg-path', '/tmp/tmpfxfk5xn8']
[2021-04-05 05:23:17,485] {standard_task_runner.py:76} INFO - Job 301: Subtask main
[2021-04-05 05:23:17,690] {logging_mixin.py:103} INFO - Running <TaskInstance: baxa_lead_importer.main 2021-04-05T05:00:00+00:00 [running]> on host airflowvm
[2021-04-05 05:23:17,863] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=baxa_lead_importer
AIRFLOW_CTX_TASK_ID=main
AIRFLOW_CTX_EXECUTION_DATE=2021-04-05T05:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-05T05:00:00+00:00
[2021-04-05 05:23:17,863] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-05 05:23:17,864] {bash.py:158} INFO - Running command: sleep 20
[2021-04-05 05:23:17,883] {bash.py:169} INFO - Output:
[2021-04-05 05:23:27,679] {local_task_job.py:169} WARNING - State of this instance has been externally set to shutdown. Terminating instance.
[2021-04-05 05:23:27,701] {process_utils.py:95} INFO - Sending Signals.SIGTERM to GPID 35065
[2021-04-05 05:23:27,701] {taskinstance.py:1214} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-04-05 05:23:27,701] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-04-05 05:23:27,731] {taskinstance.py:1396} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1295, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/operators/bash.py", line 171, in execute
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1216, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-04-05 05:23:27,742] {taskinstance.py:1433} INFO - Marking task as FAILED. dag_id=baxa_lead_importer, task_id=main, execution_date=20210405T050000, start_date=20210405T052317, end_date=20210405T052327
[2021-04-05 05:23:27,817] {process_utils.py:61} INFO - Process psutil.Process(pid=35065, status='terminated', exitcode=1, started='05:23:16') (35065) terminated with exit code 1
[2021-04-05 05:23:27,817] {process_utils.py:61} INFO - Process psutil.Process(pid=35079, status='terminated', started='05:23:17') (35079) terminated with exit code None
[2021-04-05 05:23:27,818] {local_task_job.py:118} INFO - Task exited with return code 1
